name: Release

on:
  push:
    branches:
      - main
      - 'release/*'

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install
        
      - name: Build and Test
        run: |
          pnpm build
          pnpm lint

      - name: Create npm organization if it doesn't exist
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npx npm-create-scope@latest purer-ui --token $NPM_TOKEN || true
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Prepare Release (Release Branch)
        if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
        run: |
          echo "Preparing a release on the release branch"
          pnpm changeset version
          
          if [[ -n $(git status --porcelain) ]]; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add .
            git commit -m "Version packages for release"
            git push
          fi
        
      - name: Create Release Pull Request or Publish to npm (Main Branch)
        if: ${{ github.ref == 'refs/heads/main' }}
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} 